[package]
name = "terminal"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "^6.2.0"
bytes = "^1.1.0"
